steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/task-tracker/backend:latest'
  - '.'

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/task-tracker/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY